name: ${plugin.name}
description: ${plugin.description}
author: ${plugin.author}
website: ${plugin.website}
version: ${plugin.version}
main: com.alessiodp.lastloginapi.bukkit.bootstrap.BukkitLastLoginBootstrap
api-version: 1.13
softdepend: [AuthMe, LoginSecurity, PlaceholderAPI]
libraries:
  - org.spongepowered:configurate-yaml:${libs.configurate}
  - org.spongepowered:configurate-core:${libs.configurate}
  - com.h2database:h2:${libs.h2}
  - com.zaxxer:HikariCP:${libs.hikaricp}
  - org.jdbi:jdbi3-core:${libs.jdbi}
  - org.jdbi:jdbi3-stringtemplate4:${libs.jdbi}
  - org.jdbi:jdbi3-sqlobject:${libs.jdbi}
  - org.mariadb.jdbc:mariadb-java-client:${libs.mariadb}
  - mysql:mysql-connector-java:${libs.mysql}
  - org.openjdk.nashorn:nashorn-core:${libs.nashorn}
  - org.postgresql:postgresql:${libs.postgresql}
  - org.slf4j:slf4j-api:${libs.slf4j}
  - org.slf4j:slf4j-simple:${libs.slf4j}
  - org.xerial:sqlite-jdbc:${libs.sqlite}
  - org.ow2.asm:asm:${libs.asm}
  - org.ow2.asm:asm-util:${libs.asm}
  - org.antlr:antlr-runtime:${libs.jdbi.antlr}
  - org.antlr:antlr4-runtime:${libs.jdbi.antlr4}
  - com.github.ben-manes.caffeine:caffeine:${libs.jdbi.caffeine}
  - io.leangen.geantyref:geantyref:${libs.jdbi.geantyref}
  - org.antlr:ST4:${libs.jdbi.st4}
permissions:
  lastloginapi.help:
    description: Allow access to /llapi help
  lastloginapi.info:
    description: Allow access to /llapi info
  lastloginapi.reload:
    description: Allow access to /llapi reload
  lastloginapi.version:
    description: Allow access to /llapi version
  lastloginapi.warnings:
    description: Send an alert if there is an error
  lastloginapi.*:
    default: op
    description: Can use all llapi commands
    children:
      lastloginapi.help: true
      lastloginapi.info: true
      lastloginapi.reload: true
      lastloginapi.version: true
      lastloginapi.warnings: true